# Generated by Django 5.1.6 on 2025-06-02 18:42

import django.db.models.deletion
import django.utils.timezone
import libreria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('laptop', 'Laptop'), ('impresora', 'Impresora'), ('cpu', 'CPU'), ('monitor', 'Monitor'), ('proyector', 'Proyector'), ('ups', 'UPS'), ('scanner', 'Scanner'), ('pantalla_proyector', 'Pantalla proyector'), ('tablet', 'Tablet'), ('server', 'Server'), ('router', 'Router'), ('generador_tono', 'Generador de tono'), ('tester', 'Tester'), ('multimetro', 'Multimetro'), ('access_point', 'Access point'), ('licencia_informatica', 'Licencias informáticas'), ('mouse', 'Mouse'), ('teclado', 'Teclado'), ('headset', 'Headset'), ('bocina', 'Bocina'), ('brazo_monitor', 'Brazo para monitor'), ('memoria_usb', 'Memoria USB'), ('pointer', 'Pointer'), ('kit_herramientas', 'Kit herramientas'), ('cartucho', 'Cartucho'), ('toner', 'Toner'), ('botella_tinta', 'Botella tinta'), ('camara_web', 'Cámara web'), ('disco_duro', 'Disco duro')], max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('serial', models.CharField(max_length=50, unique=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Asignado', 'Asignado')], default='Disponible', max_length=20)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True, validators=[libreria.models.validate_mac_address])),
                ('fecha_fabricacion', models.DateField(blank=True, null=True)),
                ('vida_util_anios', models.IntegerField(blank=True, null=True)),
                ('nombre_red', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('empleado_responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
                ('fecha_mantenimiento', models.DateField(blank=True, null=True)),
                ('size_pantalla', models.FloatField(blank=True, null=True)),
                ('resolucion', models.CharField(blank=True, max_length=20, null=True)),
                ('procesador_marca', models.CharField(blank=True, max_length=50, null=True)),
                ('procesador_velocidad', models.FloatField(blank=True, null=True)),
                ('procesador_generacion', models.CharField(blank=True, max_length=20, null=True)),
                ('sistema_operativo', models.CharField(blank=True, max_length=50, null=True)),
                ('sistema_operativo_version', models.CharField(blank=True, max_length=20, null=True)),
                ('sistema_operativo_bits', models.CharField(blank=True, max_length=10, null=True)),
                ('almacenamiento_capacidad', models.IntegerField(blank=True, null=True)),
                ('memoria', models.IntegerField(blank=True, null=True)),
                ('impresora_tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('impresora_velocidad_ppm', models.IntegerField(blank=True, null=True)),
                ('impresora_color', models.CharField(blank=True, max_length=3, null=True)),
                ('impresora_conexion', models.CharField(blank=True, max_length=20, null=True)),
                ('cpu_formato_diseno', models.CharField(blank=True, max_length=10, null=True)),
                ('proyector_lumens', models.IntegerField(blank=True, null=True)),
                ('ups_vatios', models.IntegerField(blank=True, null=True)),
                ('ups_fecha_bateria', models.DateField(blank=True, null=True)),
                ('scanner_velocidad', models.IntegerField(blank=True, null=True)),
                ('scanner_color', models.CharField(blank=True, max_length=10, null=True)),
                ('pantalla_proyector_tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('server_numero_procesadores', models.IntegerField(blank=True, null=True)),
                ('licencia_tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('licencia_clase', models.CharField(blank=True, max_length=20, null=True)),
                ('mouse_tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('mouse_conexion', models.CharField(blank=True, max_length=20, null=True)),
                ('clase_disco', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador_nombre', models.CharField(max_length=100)),
                ('correo_institucional', models.EmailField(max_length=254)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateField(default=django.utils.timezone.now)),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.equipo')),
            ],
        ),
    ]
