# Generated by Django 5.1.6 on 2025-07-10 15:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('laptop', 'Laptop'), ('impresora', 'Impresora'), ('cpu', 'CPU'), ('monitor', 'Monitor'), ('proyector', 'Proyector'), ('ups', 'UPS'), ('scanner', 'Scanner'), ('pantalla_proyector', 'Pantalla Proyector'), ('tablet', 'Tablet'), ('server', 'Server'), ('router', 'Router'), ('generador_tono', 'Generador de Tono'), ('tester', 'Tester'), ('multimetro', 'Multímetro'), ('access_point', 'Access Point'), ('licencia_informatica', 'Licencia Informática'), ('mouse', 'Mouse'), ('teclado', 'Teclado'), ('headset', 'Headset'), ('bocina', 'Bocina'), ('brazo_monitor', 'Brazo para Monitor'), ('memoria_usb', 'Memoria USB'), ('pointer', 'Pointer'), ('kit_herramientas', 'Kit Herramientas'), ('cartucho', 'Cartucho'), ('toner', 'Toner'), ('botella_tinta', 'Botella Tinta'), ('camara_web', 'Cámara Web'), ('disco_duro', 'Disco Duro')], max_length=50)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Asignado', 'Asignado'), ('En Mantenimiento', 'En Mantenimiento')], default='Disponible', max_length=20)),
                ('fecha_fabricacion', models.DateField(blank=True, null=True)),
                ('vida_util_anios', models.PositiveIntegerField(blank=True, null=True)),
                ('nombre_red', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion', models.CharField(default='Sin ubicación', max_length=100)),
                ('empleado_responsable', models.CharField(blank=True, default='Sin asignar', max_length=100)),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
                ('fecha_mantenimiento', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('procesador_marca', models.CharField(blank=True, max_length=100, null=True)),
                ('procesador_velocidad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('procesador_generacion', models.CharField(blank=True, max_length=50, null=True)),
                ('sistema_operativo', models.CharField(blank=True, max_length=100, null=True)),
                ('sistema_operativo_version', models.CharField(blank=True, max_length=50, null=True)),
                ('sistema_operativo_bits', models.CharField(blank=True, max_length=10, null=True)),
                ('almacenamiento_capacidad', models.PositiveIntegerField(blank=True, null=True)),
                ('memoria', models.PositiveIntegerField(blank=True, null=True)),
                ('size_pantalla', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('resolucion', models.CharField(blank=True, max_length=50, null=True)),
                ('impresora_tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('impresora_velocidad_ppm', models.PositiveIntegerField(blank=True, null=True)),
                ('impresora_color', models.BooleanField(default=False)),
                ('impresora_conexion', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu_formato_diseno', models.CharField(blank=True, default='N/A', max_length=50)),
                ('proyector_lumens', models.PositiveIntegerField(blank=True, null=True)),
                ('ups_vatios', models.PositiveIntegerField(blank=True, null=True)),
                ('ups_fecha_bateria', models.DateField(blank=True, null=True)),
                ('scanner_velocidad', models.PositiveIntegerField(blank=True, null=True)),
                ('scanner_color', models.BooleanField(default=False)),
                ('pantalla_proyector_tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('server_numero_procesadores', models.PositiveIntegerField(blank=True, null=True)),
                ('licencia_tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('licencia_clase', models.CharField(blank=True, max_length=50, null=True)),
                ('mouse_tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('mouse_conexion', models.CharField(blank=True, max_length=50, null=True)),
                ('clase_disco', models.CharField(blank=True, default='N/A', max_length=50)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador_nombre', models.CharField(max_length=100)),
                ('correo_institucional', models.EmailField(max_length=254)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateField(default=django.utils.timezone.now)),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('creado', 'Creado'), ('editado', 'Editado'), ('eliminado', 'Eliminado'), ('asignado', 'Asignado'), ('desasignado', 'Desasignado')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('serial', models.CharField(blank=True, max_length=100, null=True)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='libreria.equipo')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Equipo',
                'verbose_name_plural': 'Historial de Equipos',
            },
        ),
    ]
