# Generated by Django 5.1.6 on 2025-03-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('serial', models.CharField(max_length=100, verbose_name='Serial')),
                ('observaciones', models.CharField(max_length=100, verbose_name='Observaciones')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
