# Generated by Django 5.1.6 on 2025-07-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='colaborador_cedula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
