# Generated by Django 5.1.6 on 2025-03-07 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='serial',
            field=models.CharField(max_length=100, unique=True, verbose_name='Serial'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador_nombre', models.CharField(max_length=100, verbose_name='Nombre del colaborador')),
                ('correo_institucional', models.EmailField(max_length=254, verbose_name='Correo Institucional')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.equipo')),
            ],
        ),
    ]
