# Generated by Django 5.1.6 on 2025-06-06 14:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_alter_equipo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(default='Eliminado', max_length=20)),
                ('fecha_eliminacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('ubicacion', models.CharField(default='Sin ubicación', max_length=100)),
                ('empleado_responsable', models.CharField(default='Sin asignar', max_length=100)),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
                ('fecha_mantenimiento', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('procesador_marca', models.CharField(blank=True, max_length=100, null=True)),
                ('procesador_velocidad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('procesador_generacion', models.CharField(blank=True, max_length=50, null=True)),
                ('sistema_operativo', models.CharField(blank=True, max_length=100, null=True)),
                ('sistema_operativo_version', models.CharField(blank=True, max_length=50, null=True)),
                ('sistema_operativo_bits', models.CharField(blank=True, max_length=10, null=True)),
                ('almacenamiento_capacidad', models.PositiveIntegerField(blank=True, null=True)),
                ('memoria', models.PositiveIntegerField(blank=True, null=True)),
                ('size_pantalla', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('resolucion', models.CharField(blank=True, max_length=50, null=True)),
                ('impresora_tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('impresora_velocidad_ppm', models.PositiveIntegerField(blank=True, null=True)),
                ('impresora_color', models.BooleanField(default=False)),
                ('impresora_conexion', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu_formato_diseno', models.CharField(blank=True, default='N/A', max_length=50)),
                ('proyector_lumens', models.PositiveIntegerField(blank=True, null=True)),
                ('ups_vatios', models.PositiveIntegerField(blank=True, null=True)),
                ('ups_fecha_bateria', models.DateField(blank=True, null=True)),
                ('scanner_velocidad', models.PositiveIntegerField(blank=True, null=True)),
                ('scanner_color', models.BooleanField(default=False)),
                ('pantalla_proyector_tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('server_numero_procesadores', models.PositiveIntegerField(blank=True, null=True)),
                ('licencia_tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('licencia_clase', models.CharField(blank=True, max_length=50, null=True)),
                ('mouse_tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('mouse_conexion', models.CharField(blank=True, max_length=50, null=True)),
                ('clase_disco', models.CharField(blank=True, default='N/A', max_length=50)),
            ],
            options={
                'verbose_name': 'Historial de Equipo',
                'verbose_name_plural': 'Historial de Equipos',
            },
        ),
    ]
