# Generated by Django 5.1.6 on 2025-03-07 18:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_alter_equipo_observaciones_alter_equipo_serial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='colaborador_nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='correo_institucional',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_asignacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
