# Generated by Django 5.1.6 on 2025-03-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_alter_asignacion_colaborador_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_asignacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
