# Generated by Django 5.1.6 on 2025-06-09 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_alter_historialequipo_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialequipo',
            options={'verbose_name': 'Historial de Equipo', 'verbose_name_plural': 'Historial de Equipos'},
        ),
        migrations.RemoveField(
            model_name='historialequipo',
            name='estado',
        ),
        migrations.AddField(
            model_name='historialequipo',
            name='usuario_eliminacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_eliminados', to=settings.AUTH_USER_MODEL),
        ),
    ]
