# Generated by Django 5.1.6 on 2025-03-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_alter_asignacion_fecha_asignacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Asignado', 'Asignado')], default='Disponible', max_length=10, verbose_name='Estado'),
        ),
    ]
