# Generated by Django 5.1.6 on 2025-07-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_alter_historialequipo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='colaborador_cedula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
