# Generated by Django 5.1.6 on 2025-03-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0006_asignacion_fecha_entrega_asignacion_fecha_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='tipo',
            field=models.CharField(choices=[('laptop_pc', 'Laptop/PC'), ('celular', 'Celular'), ('impresora', 'Impresora'), ('monitor', 'Monitor')], default='laptop_pc', max_length=50),
        ),
    ]
