# Generated by Django 5.1.6 on 2025-04-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0007_alter_equipo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='tipo',
            field=models.CharField(choices=[('laptop_pc', 'Laptop/PC'), ('celular', 'Celular'), ('impresora', 'Impresora'), ('monitor', 'Monitor'), ('cables', 'cables'), ('pc', 'Pc')], default='laptop_pc', max_length=50),
        ),
    ]
