# Generated by Django 5.1.6 on 2025-04-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0008_alter_equipo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='direccion_mac',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
    ]
