# Generated by Django 5.1.6 on 2025-04-04 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0009_equipo_direccion_mac'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='direccion_mac',
            new_name='mac_address',
        ),
    ]
