# Generated by Django 5.1.6 on 2025-04-11 18:49

import libreria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0010_rename_direccion_mac_equipo_mac_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[libreria.models.validate_mac_address]),
        ),
    ]
