# Generated by Django 5.1.6 on 2025-05-30 17:45

import libreria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0011_alter_equipo_mac_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17, validators=[libreria.models.validate_mac])),
            ],
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipo',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('impresora', 'Impresora'), ('cpu', 'CPU'), ('monitor', 'Monitor'), ('proyector', 'Proyector'), ('ups', 'UPS'), ('scanner', 'Scanner'), ('pantalla_proyector', 'Pantalla proyector'), ('tablet', 'Tablet'), ('server', 'Server'), ('router', 'Router'), ('generador_tono', 'Generador de tono'), ('tester', 'Tester'), ('multimetro', 'Multimetro'), ('access_point', 'Access point'), ('licencia_informatica', 'Licencias informáticas'), ('mouse', 'Mouse'), ('teclado', 'Teclado'), ('headset', 'Headset'), ('bocina', 'Bocina'), ('brazo_monitor', 'Brazo para monitor'), ('memoria_usb', 'Memoria USB'), ('pointer', 'Pointer'), ('kit_herramientas', 'Kit herramientas'), ('cartucho', 'Cartucho'), ('toner', 'Toner'), ('botella_tinta', 'Botella tinta'), ('camara_web', 'Cámara web'), ('disco_duro', 'Disco_duro')], default='laptop_pc', max_length=50),
        ),
    ]
